file_format: "1"
id: chocofi
name: Chocofi
type: shield
url: https://github.com/pashutk/chocofi
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - chocofi_left
  - chocofi_right
